<?php

use Illuminate\Database\Seeder;

class SocietiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('societies')->insert([
            ['city_id'=>1, 'society'=> "DHA Defence",'priority'=>1,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img01.jpg"],
            ['city_id'=>1, 'society'=> "Bahria Town",'priority'=>2,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img02.jpg"],
            ['city_id'=>1, 'society'=> "Johar Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Allama Iqbal Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Askari",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Wapda Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulberg",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Eden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Cantt",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Askari",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Model Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Valencia Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "State Life Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Pak Arab Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sabzazar Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Paragon City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Faisal Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Military Accounts Housing",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "PIA Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Garden Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Punjab Coop Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Samanabad",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Township",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "EME Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulshan-e-Ravi",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Cavalry Ground",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Marghzar Officers Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bedian Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "PCSIR Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Divine Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Harbanspura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Khayaban-e-Amin",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Tariq Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ferozepur Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Multan Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bahria Orchard",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "The Spring Apartment Homes",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Central Park Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Walton Road",'priority'=>3,'important'=>1,'path'=>"web-apps/frontend/v2/images/societies/img03.jpg"],
            ['city_id'=>1, 'society'=> "Bahria Nasheman",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "BOR Board of Revenue Housing",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sheranwala Heights",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ichhra",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Taj Bagh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Punjab Govt Employees Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Architects Engineers Housing",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mughalpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulshan-e-Lahore",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "NFC 1",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lalazar",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Tajpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sui Gas Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lake City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Green City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Canal Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Icon Valley",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Izmir Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lahore Medical Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jubilee Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Baghbanpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sukh Chayn Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shahdara",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Raiwind Road",'priority'=>4,'important'=>1,'path'=>"web-apps/frontend/v2/images/societies/img04.jpg"],
            ['city_id'=>1, 'society'=> "Main Canal Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "College Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Punjab Govt Servant Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Vital Homes Housing Scheme",'priority'=>5,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img05.jpg"],
            ['city_id'=>1, 'society'=> "Air Avenue",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al-Raheem Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Garrison Homes",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Alfalah Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shadbagh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Rehman Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Revenue Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Airline Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Abdalians Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shah Jamal",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Muslim Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Garhi Shahu",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lahore Motorway City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Hafeez Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Airport Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Clifton Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nasheman-e-Iqbal",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Canal View",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nespak Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Fateh Garh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Iqbal Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Wocland Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Park View",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Punjab Small Industries Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sanda",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Awan Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Park View Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ghaziabad",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Immad Garden Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Green Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Canal Bank Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Islampura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mehar Fayaz Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "PCSIR Staff Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nawab Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "UET Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "New Muslim Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Pace Woodlands",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "HBFC Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Zaheer Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Eden Avenue Extension",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nishtar Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Dubai Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shalimar Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Medical Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Upper Mall",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Grand Avenues Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Chauburji Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nishat Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Elite Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Chungi Amar Sadhu",'priority'=>6,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img06.jpg"],
            ['city_id'=>1, 'society'=> "New Super Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Fazaia Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Iqbal Avenue",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Eden Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Green Park Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mustafa Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jail Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Super Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Thokar Niaz Baig",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Audit & Accounts Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Dream Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bund Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Hajvery Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "GT Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shalimar Link Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Guldasht Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shadman 1",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Karim Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Harbanspura Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Zaman Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bhatta Chowk",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nazir Garden Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Dharampura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Hassan Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Faisal Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "AWT Army Welfare Trust",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mansoorah",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Rahim Homes",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Walled City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sunfort Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Green Cap Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Formanites Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rehmanpura (Ferozpur Road)",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Aabpara Coop Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lahore Cantt Coop Housing",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Tricon Village",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Spring Meadows",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Wahdat Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ittifaq Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ittehad Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Wahdat Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lahore Canal Bank Cooperative",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Cantt View Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sher Shah Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sant Nagar",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Hamad Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Defence Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Atta Bakhsh Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Salaar Residency",'priority'=>7,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img07.jpg"],
            ['city_id'=>1, 'society'=> "TECH Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ali View Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Green Fort",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nayyab Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Zaman Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "PASSCO Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rail Town (Canal City)",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Kamahan Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sheraz Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lawrence Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Madina Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mohafiz Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jallo",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "PAF Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bankers Co-operative Housing",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Peco Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Ameen Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Judicial Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sunny Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ali Alam Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Allama Iqbal Intl Airport",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Chinar Bagh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Royal Residencia",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Badami Bagh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "China Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Beacon House Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ravi Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "T & T Aabpara Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Kot Lakhpat",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Daroghewala",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rehman Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Riwaz Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shabbir Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rehman Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mozang",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Royal Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Officer Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "DHA 11 Rahbar",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Altaf Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ali View Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lahore Press Club Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Naz Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Heaven Homes",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Misri Shah",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Raj Garh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shalimar Housing Scheme",'priority'=>8,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img08.jpg"],
            ['city_id'=>1, 'society'=> "P & D Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mateen Avenue",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "IEP Engineers Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Cricketer Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Davis Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Noor Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rehman Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Green Acres Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Beadon Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rajpoot Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bilal Gunj",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Army Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Muslim Nagar Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lower Mall",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Batapur",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "New Chauburji Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Saadi Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rustam Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Jalil Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Azam Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Meharpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ali Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Government Employees",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulbahar Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sherwanee Town Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jora Pull",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Anarkali",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "LDA Avenue",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Khayaban-e-Zohra",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lalazaar Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Eden Place Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Kahna",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gujjarpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Islamia Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Fort Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bismillah Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rana Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ring Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mehmood Booti",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nizamabad",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mominpur",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nisbat Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Dilkusha Gardens",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shadman ",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Aitchison Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Babar Homes",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ravi Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ghous Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gul-e-Damin",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "NFC 2",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Aashiana Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sahafi Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Wafaqi Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mian Amiruddin Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "West Wood Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulshan Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jamil Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Farooq Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rizwan Garden Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Defence Fort",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Saqib Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Iqbal Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "GOR",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Krishan Nagar",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Singhpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Canal Burg",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Toheed Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shah Kamal",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sundar Estate",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ameer-ud-Din Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Empress Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Kacha Jail Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Wassanpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "OPF Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al-Hafiz Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Real Cottages",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "DHA City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulshan-e-Ahbab",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Kot Khawaja Saeed",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mohlanwal Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rehman Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shoukat Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gawalmandi",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Hamra Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gosha-e-Ahbab",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Madina Homes",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Venus Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Madina Avenue",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Malik Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Peer Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Youhanabad",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shadab Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shershah Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Kahna Kacha",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Salli Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Abid Market",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Brandreth Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Manga - Raiwind Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bahria Education & Medical City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Dogech",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Maulana Shaukat Ali Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Excise & Taxation Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Hall Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Highcourt Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Salamatpura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sufiabad",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Haji Park Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Jannat Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sham Nagar",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulzar Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "United Bank Officers",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jalal Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sadaat Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Manawan",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jaffaria Colony",'priority'=>9,'important'=>1,'path'=>"web-apps/frontend/v2/images/societies/img09.jpg"],
            ['city_id'=>1, 'society'=> "Lytton Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bahar Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lakhodher",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulfishan Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulshan-E-Mustafa Housing",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Irum Garden Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Kotli Abdur Rahman",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Angoori Bagh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Agrics Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Siddiqia Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mason Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Karbath",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ameen Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Waris Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Saidpur",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Saroba Gardens Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Chaman Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jaffar Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Abbot Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lahore Avenue",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Doctors Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Eden Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Alpha Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Waris Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rang Mahal",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Khokhar Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gulistan Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rehmat Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "McLeod Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Waheed Brother Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Shiraz Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mian Aziz Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "National Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mushtaq Park - Phase 3",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ashiana-e-Quaid Housing Scheme",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Lakshmi Chowk",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Kareem Garden",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Canal Fort II",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Jewa Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "LDA City",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gujjar Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Expo Avenue Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Qadri Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Railway Officers Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Saggian",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Umer Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Yasrab Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Al Raheem Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Rasool Park",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Begampura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sue-e-Asal",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Qilla Gujjar Singh",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Chaudhary Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Prime Homes 1",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Dream Avenue Lahore",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Urdu Bazar",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mian Mir Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Manga Mandi",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Makkah Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Mall Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Allama Iqbal Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Gajju Matah",'priority'=>11,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img11.jpg"],
            ['city_id'=>1, 'society'=> "IBL Housing Scheme",'priority'=>12,'important'=>0,'path'=>"web-apps/frontend/v2/images/societies/img12.jpg"],
            ['city_id'=>1, 'society'=> "Gulshan Farooq Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ahmad Avenue",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Hamza Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Bahawalpur Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Pine Villas",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Ghausia Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Walton Railway Officers Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Poonch Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Aibak Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Government Transport",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Nadeem Shaheed Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Govt Officers Housing Society",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Sultan Pura",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Chah Miran",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Crescent Town",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Canal Colony",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Birdwood Road",'priority'=>0,'important'=>0,'path'=>""],
            ['city_id'=>1, 'society'=> "Temple Road",'priority'=>10,'important'=>1,'path'=>"web-apps/frontend/v2/images/societies/img10.jpg"]
        ]);
    }
}
