<?php
/**
 * Created by PhpStorm.
 * User: waqas
 * Date: 3/17/2016
 * Time: 2:30 PM
 */

return [
    'SUCCESS_MESSAGE'=>'Request completed successfully',
    'ERROR_MESSAGE'=>'Request Failed',

    'PROPERTY_PURPOSES' => [1 => 'for sale',2 => 'rent',3 => 'wanted'],
    'LAND_UNITS'=>['1'=>'square feet','2'=>'square yards','3'=>'marla','4'=>'kanal','5'=>'square meters'],
    'PROPERTIES_LIMIT' => 10,
    'AGENTS_LIMIT' => 10,
    'Banners_Limit' => [
        'property_listing'=>[
            'left'=>10,
            'right'=>10,
            'between'=>4,
            'top'=>4
        ],
        'agent-profile'=>[
            'left'=>10,
            'right'=>10,
            'between'=>4,
            'top'=>4
        ],
        'property_detail'=>[
            'left'=>10,
            'right'=>10,
            'top'=>4
        ],
        'agent_listing'=>[
            'left'=>10,
            'right'=>10,
            'top'=>4
        ],
        'index'=>[
            'left'=>10,
            'right'=>10,
            'between'=>4,
            'top'=>4
        ],
    ],
    'defaultBannerLimit'=>10,
    'Pagination' => 10,
    'PROPERTIES_SortOn' => 'id',
    'PROPERTIES_SortBy' => 'asc',
    'REGISTRATION_EMAIL_FROM'=>'info@property42.pk',
    'REGISTRATION_EMAIL_TO'=>'info@property42.pk',

    'societies' => [
        (object)[ "id"=>2 ,"name"=>'Bahria Town' ],
        (object)[ "id"=>3 ,"name"=>'Johar Town Phase 1 ' ],
        (object)[ "id"=>4 ,"name"=>'Allama Iqbal Town' ],
        (object)[ "id"=>5 ,"name"=>'Askari 1' ],
        (object)[ "id"=>6 ,"name"=>'Wapda Town' ],
        (object)[ "id"=>7 ,"name"=>'Gulberg' ],
        (object)[ "id"=>8 ,"name"=>'Eden' ],
        (object)[ "id"=>9 ,"name"=>'Cantt' ],
        (object)[ "id"=>11 ,"name"=>'Model Town' ],
        (object)[ "id"=>12 ,"name"=>'Valencia Housing Society' ],
        (object)[ "id"=>13 ,"name"=>'State Life Housing Society' ],
        (object)[ "id"=>14 ,"name"=>'Pak Arab Housing Society' ],
        (object)[ "id"=>15 ,"name"=>'Sabzazar Scheme' ],
        (object)[ "id"=>16 ,"name"=>'Paragon City' ],
        (object)[ "id"=>17 ,"name"=>'Faisal Town' ],
        (object)[ "id"=>18 ,"name"=>'Military Accounts Housing' ],
        (object)[ "id"=>19 ,"name"=>'PIA Housing Scheme' ],
        (object)[ "id"=>20 ,"name"=>'Garden Town' ],
        (object)[ "id"=>21 ,"name"=>'Punjab Coop Housing Society' ],
        (object)[ "id"=>22 ,"name"=>'Samanabad' ],
        (object)[ "id"=>23 ,"name"=>'Township' ],
        (object)[ "id"=>24 ,"name"=>'EME Society' ],
        (object)[ "id"=>25 ,"name"=>'Gulshan-e-Ravi' ],
        (object)[ "id"=>26 ,"name"=>'Cavalry Ground' ],
        (object)[ "id"=>27 ,"name"=>'Marghzar Officers Colony' ],
        (object)[ "id"=>28 ,"name"=>'Bedian Road' ],
        (object)[ "id"=>29 ,"name"=>'PCSIR Housing Scheme' ],
        (object)[ "id"=>30 ,"name"=>'Divine Gardens' ],
        (object)[ "id"=>31 ,"name"=>'Harbanspura' ],
        (object)[ "id"=>32 ,"name"=>'Khayaban-e-Amin' ],
        (object)[ "id"=>33 ,"name"=>'Tariq Gardens' ],
        (object)[ "id"=>34 ,"name"=>'Ferozepur Road' ],
        (object)[ "id"=>35 ,"name"=>'Multan Road' ],
        (object)[ "id"=>36 ,"name"=>'Bahria Orchard' ],
        (object)[ "id"=>37 ,"name"=>'The Spring Apartment Homes' ],
        (object)[ "id"=>38 ,"name"=>'Central Park Housing Scheme' ],
        (object)[ "id"=>39 ,"name"=>'Walton Road' ],
        (object)[ "id"=>40 ,"name"=>'Bahria Nasheman' ],
        (object)[ "id"=>41 ,"name"=>'BOR Board of Revenue Housing' ],
        (object)[ "id"=>42 ,"name"=>'Sheranwala Heights' ],
        (object)[ "id"=>43 ,"name"=>'Ichhra' ],
        (object)[ "id"=>44 ,"name"=>'Taj Bagh' ],
        (object)[ "id"=>45 ,"name"=>'Punjab Govt Employees Society' ],
        (object)[ "id"=>46 ,"name"=>'Architects Engineers Housing' ],
        (object)[ "id"=>47 ,"name"=>'Mughalpura' ],
        (object)[ "id"=>48 ,"name"=>'Gulshan-e-Lahore' ],
        (object)[ "id"=>49 ,"name"=>'NFC 1' ],
        (object)[ "id"=>50 ,"name"=>'Lalazar' ],
        (object)[ "id"=>51 ,"name"=>'Tajpura' ],
        (object)[ "id"=>52 ,"name"=>'Sui Gas Housing Society' ],
        (object)[ "id"=>53 ,"name"=>'Lake City' ],
        (object)[ "id"=>54 ,"name"=>'Green City' ],
        (object)[ "id"=>55 ,"name"=>'Canal Garden' ],
        (object)[ "id"=>56 ,"name"=>'Icon Valley' ],
        (object)[ "id"=>57 ,"name"=>'Izmir Town' ],
        (object)[ "id"=>58 ,"name"=>'Lahore Medical Housing Society' ],
        (object)[ "id"=>59 ,"name"=>'Jubilee Town' ],
        (object)[ "id"=>60 ,"name"=>'Baghbanpura' ],
        (object)[ "id"=>61 ,"name"=>'Sukh Chayn Gardens' ],
        (object)[ "id"=>62 ,"name"=>'Shahdara' ],
        (object)[ "id"=>63 ,"name"=>'Raiwind Road' ],
        (object)[ "id"=>64 ,"name"=>'Main Canal Road' ],
        (object)[ "id"=>65 ,"name"=>'College Road' ],
        (object)[ "id"=>66 ,"name"=>'Punjab Govt Servant Society' ],
        (object)[ "id"=>67 ,"name"=>'Vital Homes Housing Scheme' ],
        (object)[ "id"=>68 ,"name"=>'DHA Phase 8 Ex Air Avenue' ],
        (object)[ "id"=>69 ,"name"=>'Al-Raheem Garden' ],
        (object)[ "id"=>70 ,"name"=>'Garrison Homes' ],
        (object)[ "id"=>71 ,"name"=>'Alfalah Town' ],
        (object)[ "id"=>72 ,"name"=>'Shadbagh' ],
        (object)[ "id"=>73 ,"name"=>'Al Rehman Garden' ],
        (object)[ "id"=>74 ,"name"=>'Revenue Society' ],
        (object)[ "id"=>75 ,"name"=>'Airline Housing Society' ],
        (object)[ "id"=>76 ,"name"=>'Abdalians Housing Society' ],
        (object)[ "id"=>77 ,"name"=>'Shah Jamal' ],
        (object)[ "id"=>78 ,"name"=>'Muslim Town' ],
        (object)[ "id"=>79 ,"name"=>'Garhi Shahu' ],
        (object)[ "id"=>80 ,"name"=>'Lahore Motorway City' ],
        (object)[ "id"=>81 ,"name"=>'Al Hafeez Gardens' ],
        (object)[ "id"=>82 ,"name"=>'Airport Road' ],
        (object)[ "id"=>83 ,"name"=>'Clifton Colony' ],
        (object)[ "id"=>84 ,"name"=>'Nasheman-e-Iqbal' ],
        (object)[ "id"=>85 ,"name"=>'Canal View' ],
        (object)[ "id"=>86 ,"name"=>'Nespak Housing Scheme' ],
        (object)[ "id"=>87 ,"name"=>'Fateh Garh' ],
        (object)[ "id"=>88 ,"name"=>'Iqbal Park' ],
        (object)[ "id"=>89 ,"name"=>'Wocland Villas' ],
        (object)[ "id"=>90 ,"name"=>'Park View' ],
        (object)[ "id"=>91 ,"name"=>'Punjab Small Industries Colony' ],
        (object)[ "id"=>92 ,"name"=>'Sanda' ],
        (object)[ "id"=>93 ,"name"=>'Awan Town' ],
        (object)[ "id"=>94 ,"name"=>'Park View Villas' ],
        (object)[ "id"=>95 ,"name"=>'Ghaziabad' ],
        (object)[ "id"=>96 ,"name"=>'Immad Garden Housing Scheme' ],
        (object)[ "id"=>97 ,"name"=>'Green Town' ],
        (object)[ "id"=>98 ,"name"=>'Canal Bank Housing Scheme' ],
        (object)[ "id"=>99 ,"name"=>'Islampura' ],
        (object)[ "id"=>100 ,"name"=>'Mehar Fayaz Colony' ],
        (object)[ "id"=>101 ,"name"=>'PCSIR Staff Colony' ],
        (object)[ "id"=>102 ,"name"=>'Nawab Town' ],
        (object)[ "id"=>103 ,"name"=>'UET Housing Society' ],
        (object)[ "id"=>104 ,"name"=>'New Muslim Town' ],
        (object)[ "id"=>105 ,"name"=>'Pace Woodlands' ],
        (object)[ "id"=>106 ,"name"=>'HBFC Housing Society' ],
        (object)[ "id"=>107 ,"name"=>'Zaheer Villas' ],
        (object)[ "id"=>108 ,"name"=>'Eden Avenue Extension' ],
        (object)[ "id"=>109 ,"name"=>'Nishtar Colony' ],
        (object)[ "id"=>110 ,"name"=>'Dubai Town' ],
        (object)[ "id"=>111 ,"name"=>'Shalimar Town' ],
        (object)[ "id"=>112 ,"name"=>'Medical Housing Scheme' ],
        (object)[ "id"=>113 ,"name"=>'Upper Mall' ],
        (object)[ "id"=>114 ,"name"=>'Grand Avenues Housing Scheme' ],
        (object)[ "id"=>115 ,"name"=>'Chauburji Park' ],
        (object)[ "id"=>116 ,"name"=>'Nishat Colony' ],
        (object)[ "id"=>117 ,"name"=>'Elite Town' ],
        (object)[ "id"=>118 ,"name"=>'Chungi Amar Sadhu' ],
        (object)[ "id"=>119 ,"name"=>'New Super Town' ],
        (object)[ "id"=>120 ,"name"=>'Fazaia Housing Scheme' ],
        (object)[ "id"=>121 ,"name"=>'Iqbal Avenue' ],
        (object)[ "id"=>122 ,"name"=>'Eden Villas' ],
        (object)[ "id"=>123 ,"name"=>'Green Park Society' ],
        (object)[ "id"=>124 ,"name"=>'Mustafa Town' ],
        (object)[ "id"=>125 ,"name"=>'Jail Road' ],
        (object)[ "id"=>126 ,"name"=>'Super Town' ],
        (object)[ "id"=>127 ,"name"=>'Thokar Niaz Baig' ],
        (object)[ "id"=>128 ,"name"=>'Audit & Accounts Housing Society' ],
        (object)[ "id"=>129 ,"name"=>'Dream Gardens' ],
        (object)[ "id"=>130 ,"name"=>'Bund Road' ],
        (object)[ "id"=>131 ,"name"=>'Hajvery Housing Scheme' ],
        (object)[ "id"=>132 ,"name"=>'GT Road' ],
        (object)[ "id"=>133 ,"name"=>'Shalimar Link Road' ],
        (object)[ "id"=>134 ,"name"=>'Guldasht Town' ],
        (object)[ "id"=>135 ,"name"=>'Shadman 1' ],
        (object)[ "id"=>136 ,"name"=>'Karim Park' ],
        (object)[ "id"=>137 ,"name"=>'Harbanspura Road' ],
        (object)[ "id"=>138 ,"name"=>'Zaman Colony' ],
        (object)[ "id"=>139 ,"name"=>'Bhatta Chowk' ],
        (object)[ "id"=>140 ,"name"=>'Nazir Garden Society' ],
        (object)[ "id"=>141 ,"name"=>'Dharampura' ],
        (object)[ "id"=>142 ,"name"=>'Hassan Town' ],
        (object)[ "id"=>143 ,"name"=>'Al Faisal Town' ],
        (object)[ "id"=>144 ,"name"=>'AWT Army Welfare Trust' ],
        (object)[ "id"=>145 ,"name"=>'Mansoorah' ],
        (object)[ "id"=>146 ,"name"=>'Al Rahim Homes' ],
        (object)[ "id"=>147 ,"name"=>'Walled City' ],
        (object)[ "id"=>148 ,"name"=>'Sunfort Gardens' ],
        (object)[ "id"=>149 ,"name"=>'Green Cap Housing Society' ],
        (object)[ "id"=>150 ,"name"=>'Formanites Housing Scheme' ],
        (object)[ "id"=>151 ,"name"=>'Rehmanpura (Ferozpur Road)' ],
        (object)[ "id"=>152 ,"name"=>'Aabpara Coop Housing Society' ],
        (object)[ "id"=>153 ,"name"=>'Lahore Cantt Coop Housing' ],
        (object)[ "id"=>154 ,"name"=>'Tricon Village' ],
        (object)[ "id"=>155 ,"name"=>'Spring Meadows' ],
        (object)[ "id"=>156 ,"name"=>'Wahdat Road' ],
        (object)[ "id"=>157 ,"name"=>'Ittifaq Town' ],
        (object)[ "id"=>158 ,"name"=>'Ittehad Colony' ],
        (object)[ "id"=>159 ,"name"=>'Wahdat Colony' ],
        (object)[ "id"=>160 ,"name"=>'Lahore Canal Bank Cooperative' ],
        (object)[ "id"=>161 ,"name"=>'Cantt View Society' ],
        (object)[ "id"=>162 ,"name"=>'Sher Shah Colony' ],
        (object)[ "id"=>163 ,"name"=>'Sant Nagar' ],
        (object)[ "id"=>164 ,"name"=>'Al Hamad Colony' ],
        (object)[ "id"=>165 ,"name"=>'Defence Road' ],
        (object)[ "id"=>166 ,"name"=>'Atta Bakhsh Road' ],
        (object)[ "id"=>167 ,"name"=>'Salaar Residency' ],
        (object)[ "id"=>168 ,"name"=>'TECH Society' ],
        (object)[ "id"=>169 ,"name"=>'Ali View Park' ],
        (object)[ "id"=>170 ,"name"=>'Green Fort' ],
        (object)[ "id"=>171 ,"name"=>'Nayyab Villas' ],
        (object)[ "id"=>172 ,"name"=>'Zaman Park' ],
        (object)[ "id"=>173 ,"name"=>'PASSCO Housing Society' ],
        (object)[ "id"=>174 ,"name"=>'Rail Town (Canal City)' ],
        (object)[ "id"=>175 ,"name"=>'Kamahan Road' ],
        (object)[ "id"=>176 ,"name"=>'Sheraz Town' ],
        (object)[ "id"=>177 ,"name"=>'Lawrence Road' ],
        (object)[ "id"=>178 ,"name"=>'Madina Colony' ],
        (object)[ "id"=>179 ,"name"=>'Mohafiz Town' ],
        (object)[ "id"=>180 ,"name"=>'Jallo' ],
        (object)[ "id"=>181 ,"name"=>'PAF Society' ],
        (object)[ "id"=>182 ,"name"=>'Bankers Co-operative Housing' ],
        (object)[ "id"=>183 ,"name"=>'Peco Road' ],
        (object)[ "id"=>184 ,"name"=>'Al Ameen Society' ],
        (object)[ "id"=>185 ,"name"=>'Judicial Colony' ],
        (object)[ "id"=>186 ,"name"=>'Sunny Park' ],
        (object)[ "id"=>187 ,"name"=>'Ali Alam Garden' ],
        (object)[ "id"=>188 ,"name"=>'Allama Iqbal Intl Airport' ],
        (object)[ "id"=>189 ,"name"=>'Chinar Bagh' ],
        (object)[ "id"=>190 ,"name"=>'Royal Residencia' ],
        (object)[ "id"=>191 ,"name"=>'Badami Bagh' ],
        (object)[ "id"=>192 ,"name"=>'China Scheme' ],
        (object)[ "id"=>193 ,"name"=>'Beacon House Society' ],
        (object)[ "id"=>194 ,"name"=>'Ravi Road' ],
        (object)[ "id"=>195 ,"name"=>'T & T Aabpara Housing Society' ],
        (object)[ "id"=>196 ,"name"=>'Kot Lakhpat' ],
        (object)[ "id"=>197 ,"name"=>'Daroghewala' ],
        (object)[ "id"=>198 ,"name"=>'Rehman Gardens' ],
        (object)[ "id"=>199 ,"name"=>'Riwaz Garden' ],
        (object)[ "id"=>200 ,"name"=>'Shabbir Town' ],
        (object)[ "id"=>201 ,"name"=>'Rehman Villas' ],
        (object)[ "id"=>202 ,"name"=>'Mozang' ],
        (object)[ "id"=>203 ,"name"=>'Royal Garden' ],
        (object)[ "id"=>204 ,"name"=>'Officer Colony' ],
        (object)[ "id"=>206 ,"name"=>'Altaf Colony' ],
        (object)[ "id"=>207 ,"name"=>'Ali View Garden' ],
        (object)[ "id"=>208 ,"name"=>'Lahore Press Club Housing Scheme' ],
        (object)[ "id"=>209 ,"name"=>'Naz Town' ],
        (object)[ "id"=>210 ,"name"=>'Heaven Homes' ],
        (object)[ "id"=>211 ,"name"=>'Misri Shah' ],
        (object)[ "id"=>212 ,"name"=>'Raj Garh' ],
        (object)[ "id"=>213 ,"name"=>'Shalimar Housing Scheme' ],
        (object)[ "id"=>214 ,"name"=>'P & D Housing Society' ],
        (object)[ "id"=>215 ,"name"=>'Mateen Avenue' ],
        (object)[ "id"=>216 ,"name"=>'IEP Engineers Town' ],
        (object)[ "id"=>217 ,"name"=>'Cricketer Villas' ],
        (object)[ "id"=>218 ,"name"=>'Davis Road' ],
        (object)[ "id"=>219 ,"name"=>'Al Noor Town' ],
        (object)[ "id"=>220 ,"name"=>'Rehman Park' ],
        (object)[ "id"=>221 ,"name"=>'Green Acres Housing Society' ],
        (object)[ "id"=>222 ,"name"=>'Beadon Road' ],
        (object)[ "id"=>223 ,"name"=>'Rajpoot Town' ],
        (object)[ "id"=>224 ,"name"=>'Bilal Gunj' ],
        (object)[ "id"=>225 ,"name"=>'Army Housing Society' ],
        (object)[ "id"=>226 ,"name"=>'Muslim Nagar Housing Scheme' ],
        (object)[ "id"=>227 ,"name"=>'Lower Mall' ],
        (object)[ "id"=>228 ,"name"=>'Batapur' ],
        (object)[ "id"=>229 ,"name"=>'New Chauburji Park' ],
        (object)[ "id"=>230 ,"name"=>'Saadi Park' ],
        (object)[ "id"=>231 ,"name"=>'Rustam Park' ],
        (object)[ "id"=>232 ,"name"=>'Al Jalil Garden' ],
        (object)[ "id"=>233 ,"name"=>'Azam Gardens' ],
        (object)[ "id"=>234 ,"name"=>'Meharpura' ],
        (object)[ "id"=>235 ,"name"=>'Ali Town' ],
        (object)[ "id"=>236 ,"name"=>'Government Employees' ],
        (object)[ "id"=>237 ,"name"=>'Gulbahar Colony' ],
        (object)[ "id"=>238 ,"name"=>'Sherwanee Town Housing Scheme' ],
        (object)[ "id"=>239 ,"name"=>'Jora Pull' ],
        (object)[ "id"=>240 ,"name"=>'Anarkali' ],
        (object)[ "id"=>241 ,"name"=>'LDA Avenue' ],
        (object)[ "id"=>242 ,"name"=>'Khayaban-e-Zohra' ],
        (object)[ "id"=>243 ,"name"=>'Lalazaar Garden' ],
        (object)[ "id"=>244 ,"name"=>'Eden Place Housing Scheme' ],
        (object)[ "id"=>245 ,"name"=>'Kahna' ],
        (object)[ "id"=>246 ,"name"=>'Gujjarpura' ],
        (object)[ "id"=>247 ,"name"=>'Islamia Park' ],
        (object)[ "id"=>248 ,"name"=>'Fort Villas' ],
        (object)[ "id"=>249 ,"name"=>'Bismillah Housing Scheme' ],
        (object)[ "id"=>250 ,"name"=>'Rana Town' ],
        (object)[ "id"=>251 ,"name"=>'Ring Road' ],
        (object)[ "id"=>252 ,"name"=>'Mehmood Booti' ],
        (object)[ "id"=>253 ,"name"=>'Nizamabad' ],
        (object)[ "id"=>254 ,"name"=>'Mominpur' ],
        (object)[ "id"=>255 ,"name"=>'Nisbat Road' ],
        (object)[ "id"=>256 ,"name"=>'Dilkusha Gardens' ],
        (object)[ "id"=>257 ,"name"=>'Shadman ' ],
        (object)[ "id"=>258 ,"name"=>'Aitchison Society' ],
        (object)[ "id"=>259 ,"name"=>'Babar Homes' ],
        (object)[ "id"=>260 ,"name"=>'Ravi Park' ],
        (object)[ "id"=>261 ,"name"=>'Ghous Garden' ],
        (object)[ "id"=>262 ,"name"=>'Gul-e-Damin' ],
        (object)[ "id"=>263 ,"name"=>'NFC 2' ],
        (object)[ "id"=>264 ,"name"=>'Aashiana Road' ],
        (object)[ "id"=>265 ,"name"=>'Sahafi Colony' ],
        (object)[ "id"=>266 ,"name"=>'Wafaqi Colony' ],
        (object)[ "id"=>267 ,"name"=>'Mian Amiruddin Park' ],
        (object)[ "id"=>268 ,"name"=>'West Wood Housing Society' ],
        (object)[ "id"=>269 ,"name"=>'Gulshan Colony' ],
        (object)[ "id"=>270 ,"name"=>'Jamil Town' ],
        (object)[ "id"=>271 ,"name"=>'Farooq Colony' ],
        (object)[ "id"=>272 ,"name"=>'Rizwan Garden Scheme' ],
        (object)[ "id"=>273 ,"name"=>'Defence Fort' ],
        (object)[ "id"=>274 ,"name"=>'Saqib Town' ],
        (object)[ "id"=>275 ,"name"=>'Iqbal Colony' ],
        (object)[ "id"=>276 ,"name"=>'GOR' ],
        (object)[ "id"=>277 ,"name"=>'Krishan Nagar' ],
        (object)[ "id"=>278 ,"name"=>'Singhpura' ],
        (object)[ "id"=>279 ,"name"=>'Canal Burg' ],
        (object)[ "id"=>280 ,"name"=>'Toheed Park' ],
        (object)[ "id"=>281 ,"name"=>'Shah Kamal' ],
        (object)[ "id"=>282 ,"name"=>'Sundar Estate' ],
        (object)[ "id"=>283 ,"name"=>'Ameer-ud-Din Park' ],
        (object)[ "id"=>284 ,"name"=>'Empress Road' ],
        (object)[ "id"=>285 ,"name"=>'Kacha Jail Road' ],
        (object)[ "id"=>286 ,"name"=>'Wassanpura' ],
        (object)[ "id"=>287 ,"name"=>'OPF Housing Scheme' ],
        (object)[ "id"=>288 ,"name"=>'Al-Hafiz Town' ],
        (object)[ "id"=>289 ,"name"=>'Real Cottages' ],
        (object)[ "id"=>291 ,"name"=>'Gulshan-e-Ahbab' ],
        (object)[ "id"=>292 ,"name"=>'Kot Khawaja Saeed' ],
        (object)[ "id"=>293 ,"name"=>'Mohlanwal Scheme' ],
        (object)[ "id"=>294 ,"name"=>'Rehman Housing Society' ],
        (object)[ "id"=>295 ,"name"=>'Shoukat Town' ],
        (object)[ "id"=>296 ,"name"=>'Gawalmandi' ],
        (object)[ "id"=>297 ,"name"=>'Al Hamra Town' ],
        (object)[ "id"=>298 ,"name"=>'Gosha-e-Ahbab' ],
        (object)[ "id"=>299 ,"name"=>'Madina Homes' ],
        (object)[ "id"=>300 ,"name"=>'Venus Housing Scheme' ],
        (object)[ "id"=>301 ,"name"=>'Al Madina Avenue' ],
        (object)[ "id"=>302 ,"name"=>'Malik Park' ],
        (object)[ "id"=>303 ,"name"=>'Peer Colony' ],
        (object)[ "id"=>304 ,"name"=>'Youhanabad' ],
        (object)[ "id"=>305 ,"name"=>'Shadab Garden' ],
        (object)[ "id"=>306 ,"name"=>'Shershah Colony' ],
        (object)[ "id"=>307 ,"name"=>'Kahna Kacha' ],
        (object)[ "id"=>308 ,"name"=>'Salli Town' ],
        (object)[ "id"=>309 ,"name"=>'Abid Market' ],
        (object)[ "id"=>310 ,"name"=>'Brandreth Road' ],
        (object)[ "id"=>311 ,"name"=>'Manga - Raiwind Road' ],
        (object)[ "id"=>312 ,"name"=>'Bahria Education & Medical City' ],
        (object)[ "id"=>313 ,"name"=>'Dogech' ],
        (object)[ "id"=>314 ,"name"=>'Maulana Shaukat Ali Road' ],
        (object)[ "id"=>315 ,"name"=>'Excise & Taxation Housing Scheme' ],
        (object)[ "id"=>316 ,"name"=>'Hall Road' ],
        (object)[ "id"=>317 ,"name"=>'Highcourt Society' ],
        (object)[ "id"=>318 ,"name"=>'Salamatpura' ],
        (object)[ "id"=>319 ,"name"=>'Sufiabad' ],
        (object)[ "id"=>320 ,"name"=>'Haji Park Housing Scheme' ],
        (object)[ "id"=>321 ,"name"=>'Al Jannat Housing Scheme' ],
        (object)[ "id"=>322 ,"name"=>'Sham Nagar' ],
        (object)[ "id"=>323 ,"name"=>'Gulzar Colony' ],
        (object)[ "id"=>324 ,"name"=>'United Bank Officers' ],
        (object)[ "id"=>325 ,"name"=>'Jalal Colony' ],
        (object)[ "id"=>326 ,"name"=>'Sadaat Town' ],
        (object)[ "id"=>327 ,"name"=>'Manawan' ],
        (object)[ "id"=>328 ,"name"=>'Jaffaria Colony' ],
        (object)[ "id"=>329 ,"name"=>'Lytton Road' ],
        (object)[ "id"=>330 ,"name"=>'Bahar Colony' ],
        (object)[ "id"=>331 ,"name"=>'Lakhodher' ],
        (object)[ "id"=>332 ,"name"=>'Gulfishan Town' ],
        (object)[ "id"=>333 ,"name"=>'Gulshan-E-Mustafa Housing' ],
        (object)[ "id"=>334 ,"name"=>'Irum Garden Housing Society' ],
        (object)[ "id"=>335 ,"name"=>'Kotli Abdur Rahman' ],
        (object)[ "id"=>336 ,"name"=>'Angoori Bagh' ],
        (object)[ "id"=>337 ,"name"=>'Agrics Town' ],
        (object)[ "id"=>338 ,"name"=>'Siddiqia Colony' ],
        (object)[ "id"=>339 ,"name"=>'Mason Road' ],
        (object)[ "id"=>340 ,"name"=>'Karbath' ],
        (object)[ "id"=>341 ,"name"=>'Ameen Park' ],
        (object)[ "id"=>342 ,"name"=>'Waris Road' ],
        (object)[ "id"=>343 ,"name"=>'Saidpur' ],
        (object)[ "id"=>344 ,"name"=>'Saroba Gardens Housing Society' ],
        (object)[ "id"=>345 ,"name"=>'Chaman Park' ],
        (object)[ "id"=>346 ,"name"=>'Jaffar Town' ],
        (object)[ "id"=>347 ,"name"=>'Abbot Road' ],
        (object)[ "id"=>348 ,"name"=>'Lahore Avenue' ],
        (object)[ "id"=>349 ,"name"=>'Doctors Housing Society' ],
        (object)[ "id"=>350 ,"name"=>'Eden Park' ],
        (object)[ "id"=>351 ,"name"=>'Alpha Society' ],
        (object)[ "id"=>352 ,"name"=>'Waris Colony' ],
        (object)[ "id"=>353 ,"name"=>'Rang Mahal' ],
        (object)[ "id"=>354 ,"name"=>'Khokhar Town' ],
        (object)[ "id"=>355 ,"name"=>'Gulistan Colony' ],
        (object)[ "id"=>356 ,"name"=>'Rehmat Colony' ],
        (object)[ "id"=>357 ,"name"=>'McLeod Road' ],
        (object)[ "id"=>358 ,"name"=>'Waheed Brother Colony' ],
        (object)[ "id"=>359 ,"name"=>'Shiraz Villas' ],
        (object)[ "id"=>360 ,"name"=>'Mian Aziz Garden' ],
        (object)[ "id"=>361 ,"name"=>'National Town' ],
        (object)[ "id"=>362 ,"name"=>'Mushtaq Park - Phase 3' ],
        (object)[ "id"=>363 ,"name"=>'Ashiana-e-Quaid Housing Scheme' ],
        (object)[ "id"=>364 ,"name"=>'Lakshmi Chowk' ],
        (object)[ "id"=>365 ,"name"=>'Al Kareem Garden' ],
        (object)[ "id"=>366 ,"name"=>'Canal Fort II' ],
        (object)[ "id"=>367 ,"name"=>'Jewa Town' ],
        (object)[ "id"=>368 ,"name"=>'LDA City' ],
        (object)[ "id"=>369 ,"name"=>'Gujjar Colony' ],
        (object)[ "id"=>370 ,"name"=>'Expo Avenue Society' ],
        (object)[ "id"=>371 ,"name"=>'Qadri Colony' ],
        (object)[ "id"=>372 ,"name"=>'Railway Officers Colony' ],
        (object)[ "id"=>373 ,"name"=>'Saggian' ],
        (object)[ "id"=>374 ,"name"=>'Umer Colony' ],
        (object)[ "id"=>375 ,"name"=>'Yasrab Colony' ],
        (object)[ "id"=>376 ,"name"=>'Al Raheem Town' ],
        (object)[ "id"=>377 ,"name"=>'Rasool Park' ],
        (object)[ "id"=>378 ,"name"=>'Begampura' ],
        (object)[ "id"=>379 ,"name"=>'Sue-e-Asal' ],
        (object)[ "id"=>380 ,"name"=>'Qilla Gujjar Singh' ],
        (object)[ "id"=>381 ,"name"=>'Chaudhary Colony' ],
        (object)[ "id"=>382 ,"name"=>'Prime Homes 1' ],
        (object)[ "id"=>383 ,"name"=>'Dream Avenue Lahore' ],
        (object)[ "id"=>384 ,"name"=>'Urdu Bazar' ],
        (object)[ "id"=>385 ,"name"=>'Mian Mir Colony' ],
        (object)[ "id"=>386 ,"name"=>'Manga Mandi' ],
        (object)[ "id"=>387 ,"name"=>'Makkah Colony' ],
        (object)[ "id"=>388 ,"name"=>'Mall Road' ],
        (object)[ "id"=>389 ,"name"=>'Allama Iqbal Road' ],
        (object)[ "id"=>390 ,"name"=>'Gajju Matah' ],
        (object)[ "id"=>391 ,"name"=>'IBL Housing Scheme' ],
        (object)[ "id"=>392 ,"name"=>'Gulshan Farooq Colony' ],
        (object)[ "id"=>393 ,"name"=>'Ahmad Avenue' ],
        (object)[ "id"=>394 ,"name"=>'Hamza Town' ],
        (object)[ "id"=>395 ,"name"=>'Bahawalpur Road' ],
        (object)[ "id"=>396 ,"name"=>'Pine Villas' ],
        (object)[ "id"=>397 ,"name"=>'Ghausia Colony' ],
        (object)[ "id"=>398 ,"name"=>'Walton Railway Officers Colony' ],
        (object)[ "id"=>399 ,"name"=>'Poonch Road' ],
        (object)[ "id"=>400 ,"name"=>'Aibak Road' ],
        (object)[ "id"=>401 ,"name"=>'Government Transport' ],
        (object)[ "id"=>402 ,"name"=>'Nadeem Shaheed Road' ],
        (object)[ "id"=>403 ,"name"=>'Govt Officers Housing Society' ],
        (object)[ "id"=>404 ,"name"=>'Sultan Pura' ],
        (object)[ "id"=>405 ,"name"=>'Chah Miran' ],
        (object)[ "id"=>406 ,"name"=>'Crescent Town' ],
        (object)[ "id"=>407 ,"name"=>'Canal Colony' ],
        (object)[ "id"=>408 ,"name"=>'Birdwood Road' ],
        (object)[ "id"=>409 ,"name"=>'Temple Road' ],
        (object)[ "id"=>410 ,"name"=>'DHA Phase 1' ],
        (object)[ "id"=>411 ,"name"=>'DHA Phase 2' ],
        (object)[ "id"=>412 ,"name"=>'DHA Phase 3' ],
        (object)[ "id"=>413 ,"name"=>'DHA Phase 4' ],
        (object)[ "id"=>414 ,"name"=>'DHA Phase 5' ],
        (object)[ "id"=>415 ,"name"=>'DHA Phase 6' ],
        (object)[ "id"=>416 ,"name"=>'DHA Phase 7' ],
        (object)[ "id"=>417 ,"name"=>'DHA Phase 8' ],
        (object)[ "id"=>418 ,"name"=>'DHA Phase 9 Town' ],
        (object)[ "id"=>419 ,"name"=>'DHA Phase 9 Prism' ],
        (object)[ "id"=>421 ,"name"=>'DHA Phase 11 (Halloki Garden) ' ],
        (object)[ "id"=>422 ,"name"=>'Defence Raya' ],
        (object)[ "id"=>423 ,"name"=>'DHA Rahber Phase1' ],
        (object)[ "id"=>424 ,"name"=>'DHA Rahber Phase 2' ],
        (object)[ "id"=>425 ,"name"=>'DHA Rahber Phase 2-EXT' ],
        (object)[ "id"=>426 ,"name"=>'DHA EME' ],
        (object)[ "id"=>427 ,"name"=>'DHA Phase 8 Broadway Commercial' ],
        (object)[ "id"=>428 ,"name"=>'Johar Town Phase 2' ],
        (object)[ "id"=>429 ,"name"=>'Askari 2' ],
        (object)[ "id"=>430 ,"name"=>'Askari 3' ],
        (object)[ "id"=>431 ,"name"=>'Askari 5' ],
        (object)[ "id"=>432 ,"name"=>'Askari 8' ],
        (object)[ "id"=>433 ,"name"=>'Askari 9' ],
        (object)[ "id"=>434 ,"name"=>'Askari 10' ],
        (object)[ "id"=>435 ,"name"=>'Askari 11' ],
        (object)[ "id"=>436 ,"name"=>'Askari Villas-Shami Road' ],
        (object)[ "id"=>437 ,"name"=>'Askari Housing - Sarwar Road' ],
    ]
];